### PR TITLE
Fix #3: Create base template UI

### LINKED ISSUE #3: Create base template UI
Nothing fancy, start by mimic'ing https://oauth-stable.dev.lcip.org/console/clients layout & styles.

### PR DESCRIPTION
**Pull request by openjck**

### CODE REVIEW

**Comment by openjck** [comment]
I don't recommend using Skeleton in the long term, but this gets us up-and-running with something for now. Skeleton is pretty unobtrusive (it mostly just implements a grid and styles common elements like `<button>`) so we can easily replace it with something better once we have a designer.

**Comment by groovecoder** [comment]
Works. Can we merge and file a follow-up for styling like the FxA Oauth console?

fxa-oauth-style

**Comment by openjck** [comment]
Sure thing. Sorry for misunderstanding. I didn't realize how closely we wanted to match their style. Would we want to mirror their style for the long term or do you think we'll get time from a designer in the future?

Before we merge this, I'd also like to figure out how to get Heroku to install Bower packages and run `collectstatic` at deploy time. I haven't found any great documentation but I'll keep looking. Do you happen to know off-hand of a standard way of doing this?

**Comment by groovecoder** [comment]
As far as I can tell, we should plan and build on the assumption we will **not** have any dedicated design bandwidth for this. If we do get dedicated design bandwidth for developer-facing services projects, we can (re-)design both the push service dashboard, and the fxa oauth client dashboard at the same time.

I think we can add an [`app.json`](https://devcenter.heroku.com/articles/app-json-schema) file with a `scripts.postdeploy` section to run things like bower, collectstatic, and django migrations.

**Comment by groovecoder** [comment]
But, the commands in `scripts.postdeploy` are, I think, run in one-off dynos. I'm not sure if their file outputs will be shared with the web dyno? Might have to do some digging about how that works (with django-whitenoise)?

**Comment by groovecoder** [comment]
So, should I merge now? Or wait until we sort out the `collectstatic` and `bower` commands during deploys?

**Comment by groovecoder** [comment]
Bah, `scripts.postdeploy` won't work ...

> The postdeploy script is run once, after the app is created and not on subsequent deploys to the app

**Comment by groovecoder** [comment]
And dang, we can't run bower on heroku unless we use [a custom python + node heroku buildback](https://github.com/jhardie/python-brunch-bower-buildpack)

**Comment by groovecoder** [comment]
```
(push-dev-dashboard)lcrouch:push-dev-dashboard lcrouch$ bower install
bower                           ENOENT No bower.json present
```

**Comment by groovecoder** [comment]
Superseded by https://github.com/groovecoder/push-dev-dashboard/pull/32

**Pull request closed without merging**
