### PR TITLE
Add sentry integration for traceback reporting

### LINKED ISSUE #188: Add sentry for error/traceback logging

### PR DESCRIPTION
**Pull request by oremj**
Fixes #188

### CODE REVIEW

**Comment by oremj** [comment]
@groovecoder r?

**Comment by groovecoder** [comment]
Looks good. I added this to https://github.com/mozilla-services/push-dev-dashboard/issues/147 and I'll spot-check it now to make sure there are no regressions.

**Comment by groovecoder** [comment]
No issues ... is this config known work for other django projects? How can I test? Can I set this env var to a dev sentry server on the dev dashboard instance to check it?

**Comment by oremj** [comment]
It should be good. I got the config from https://getsentry.com/for/django/. We do something similar for AMO. I'll test on stage shortly.

**Comment by groovecoder** [comment]
Would I be able to send dev server/instance/cluster tracebacks to the stage sentry server too?

**Comment by oremj** [comment]
@jasonthomas ^?

**Comment by jasonthomas** [comment]
This should be fine. We just need to create a unique project just for the dev instance.

**Pull request merged**
