### PR TITLE
update Django to 1.9.10 security release

### PR DESCRIPTION
**Pull request by groovecoder**

### CODE REVIEW

**Comment by groovecoder** [comment]
@oremj we should push (a tag of) this latest master merge to stage & prod to ensure the security fix is in both environments.

**Comment by groovecoder** [comment]
ping @oremj: were you able to push this latest version to stage (& prod)?

**Comment by oremj** [comment]
Is this still considered an active product? It was never set up in production.

**Comment by groovecoder** [comment]
Ah, okay. No worries then. I'll un-assign. The code is merged anyway, so if/when this goes out, the latest code has the latest security fix.

**Comment by oremj** [comment]
Sounds good!

**Pull request merged**
