### PR TITLE
Add Google Analytics (with event tracking for sign in clicks!)

### PR DESCRIPTION
**Pull request by groovecoder**
To spot-check, set `GOOGLE_ANALYTICS_ACCOUNT=UA-36116321-18` in the `.env` file, and visit the site ...
1. Because `DEBUG=True`, you should see GA output in the console
2. Click a "Sign in with Firefox Account" button - you should see an event track in the console

### CODE REVIEW

**Comment by openjck** [comment]
I can see the page is using the __debug_ script, but I'm not seeing anything in the console. What should I be seeing?

**Comment by groovecoder** [comment]
If your console logging level set to include warnings & info messages, you should see ...

dev-dash-ga-debug

**Comment by openjck** [comment]
Strange, I have warnings and info enabled in Firefox Developer Tools, but the message doesn't appear. Works fine in Chrome though. :confused:

**Comment by openjck** [comment]
Ah, Disconnect.me was blocking GA. That'd do it.

**Pull request merged**
