### PR TITLE
Fix #172: Enable WhiteNoise

### PR DESCRIPTION
**Pull request by openjck**

### CODE REVIEW

**Comment by openjck** [comment]
The one thing this is missing is a _production mode_ like we have on MDN. We can set `DJANGO_DEBUG=False` but nothing serves up the files in _/static_. I'll have to keep thinking about it.

**Comment by groovecoder** [comment]
We still have the problem where the pipeline-generated `css/dashboard.css` and `js/dashboard.js` aren't served by whitenoise.

I.e., with `DJANGO_DEBUG=False`, whitenoise collects the individual static files and serve them (e.g., `applications.3f46d1c0875e.css`, `details.e54257cd969c.css`, etc.) but it doesn't create the necessary `dashboard.6d344fe82057.css` combined file to serve.

**Comment by openjck** [comment]
Ah, good catch. Fixed. Testing in production mode is a lot easier than I thought, too.

**Comment by groovecoder** [comment]
Ah, looks good now.

**Pull request merged**
