### PR TITLE
Fix #144: Shrinkwrap NPM dependencies

### LINKED ISSUE #144: shrinkwrap npm dependencies
After the pad-left fiasco, I say we should shrinkwrap our npm dependencies.

### PR DESCRIPTION
**Pull request by openjck**

### CODE REVIEW

**Comment by openjck** [comment]
My understanding is that once this is merged, we would continue running `npm install --save` like always. The shrinkwrap file will be updated automatically as we go.

The one caveat is that you might need to `rm -rf node_modules` before using the shrinkwrap file for the first time, and maybe when you switch branches.

**Comment by groovecoder** [comment]
Broken front-style job looks legit - Travis is having trouble `npm install`ing now?

**Comment by pdehaan** [comment]
This is kind of interesting... From the Travis-CI logs:

```
-npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.0.9
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64
npm ERR! System Linux 3.13.0-40-generic
npm ERR! command "/home/travis/.nvm/v0.10.36/bin/node" "/home/travis/.nvm/v0.10.36/bin/npm" "install"
npm ERR! cwd /home/travis/build/mozilla-services/push-dev-dashboard
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code EBADPLATFORM
```

FWIW, Node 0.10 and npm 1.x are ancient. Not sure the best way to try and update those from within Tox env.

Although I somewhat doubt that is the core issue. Looking at the failing [**fsevents**](https://www.npmjs.com/package/fsevents) module, there is an odd reference to "Valid OS: darwin" and "Actual OS: linux".

Looking at the [**fsevents** module on npm](https://www.npmjs.com/package/fsevents) it says:

> **Native Access to Mac OS-X FSEvents**
> The FSEvents API in OS X allows applications to register for notifications of changes to a given directory tree. It is a very fast and lightweight alternative to kqueue.

**Comment by pdehaan** [comment]
Further down the rabbit hole... It doesn't look like tox is too interesting. Just a simple `npm test`:

``` ini
[testenv:front-style]
whitelist_externals =
    npm
commands =
    npm install
    npm test
```

&mdash; via [/tox.ini:22-27](https://github.com/mozilla-services/push-dev-dashboard/blob/a334d6bf021658d392ec5e403ca81d45d1ae80b3/tox.ini#L22-L27)

---

Looking at [`npm test` in package.json](https://github.com/mozilla-services/push-dev-dashboard/blob/a334d6bf021658d392ec5e403ca81d45d1ae80b3/package.json#L2-L4) it looks like it just runs ESLint and stylint:

``` js
  "scripts": {
    "test": "eslint --ignore-pattern 'staticfiles/**/*.js' --ignore-pattern 'env/**/*.js' .; stylint **/static/styles/*.styl"
  },
```

**NOTE:** We should probably use an .eslintignore file instead of using the `--ignore-pattern` flag here.

I can't tell from the shrinkwrap file which of the 5 [dev]dependencies is trying to install **fsevent**. Not sure if the current shrinkwrap file is using npm3, which may explain why it looks so flat.

**Comment by pdehaan** [comment]
> The shrinkwrap file will be updated automatically as we go.

IIRC, I think this is only the case if you're using npm@3 (which you'd need to install manually, or use Node 5+). Ref: `https://github.com/npm/npm/issues/5083`

**Comment by openjck** [comment]
Tests are passing. I think [this tip](https://github.com/travis-ci/travis-ci/issues/4653#issuecomment-194051953) about forcing Travis to use NPM 3 helped.

**Comment by openjck** [comment]
I'm still a little unclear about exactly what we'll need to do differently now that we have a shrinkwrap file, but it might come down to removing `node_modules` every now and then, like when switching branches. We can play it by ear.

**Pull request merged**
