### PR TITLE
Move button for managing applications to new menu

### PR DESCRIPTION
**Pull request by openjck**

### CODE REVIEW

**Comment by groovecoder** [comment]
This is a cool direction. I like the idea of having a "Push" section of the dashboard, and a navigation menu item for it.

What if the nav & section hierarchy are:
- Push: `/push/`
  - status widget
  - signed-out: + "Sign in to manage your push applications"
  - signed-in: + "Manage your push applications"
  - Applications: `/push/apps`
    - Requires signed-in
    - App table
    - Form to create new app
    - {Name}: `/push/apps/{pk}`
      - Requires signed-in
      - Application details (Name, VAPID Status, Token)
      - Validation form

It's clumsy right now since we don't have any other sections, but let me see if I can at least find some other datadog dashboards we could put on the home page ...

**Comment by groovecoder** [comment]
More potential Datadog widgets that could interest Firefox developers ...
- addons.mozilla.org status/response time
- Marketplace status/response time
- FxA auth server status/response time

**Comment by openjck** [comment]
Yeah, putting the application list under _/push/apps_ makes sense to me. That would free up _/push_ to be a landing page for the push service with a status widget and other general-purpose information. I'll take a look at it now.

**Comment by openjck** [comment]
Superseded by #84

**Pull request closed without merging**
