### PR TITLE
fix #1: disable email verification

### LINKED ISSUE #1: Sign in with FxA returns 500 until 2nd time
Steps to reproduce:
1. Sign in with Firefox Account

Expected results:
Sign-in completes without error

Actual results:
Server Error (500)

Notes:
If you try to sign in again with the same FxA, there's no 500 error anymore and the home page shows "Hello FxA user: lcrouch"

### PR DESCRIPTION
**Pull request by groovecoder**

### CODE REVIEW

**Comment by groovecoder** [comment]
@openjck can you try this one too?

**Comment by openjck** [comment]
I was able to reproduce the issue, but unfortunately now get this error when trying to start the server, even after rebooting and un-installing/re-installing the dashboard:

```
django.db.utils.OperationalError: could not connect to server: No such file or directory
    Is the server running locally and accepting
    connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```

I notice there are also some errors when the pip install is run. Do you think this could be related?

```
  File "/[...]/push-dev-dashboard/env/build/Django/django/conf/app_template/apps.py", line 1
    {{ unicode_literals }}from django.apps import AppConfig
                             ^
SyntaxError: invalid syntax
```

**Comment by groovecoder** [comment]
Oops, rebased this on master so it now uses sqlite database by default instead of postgres. Which means you'll need to re-migrate and re-create the super user again (in the sqlite db).

**Comment by openjck** [comment]
Looks good r+

**Pull request merged**
